image: node:7.10.0

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - mkdir dist
  - yarn install --production=false
  - yarn run build:prod
  artifacts:
    paths:
    - node_modules/
    - dist

test:
  stage: test
  script:
  - yarn run test
  allow_failure: true

lint:
  stage: test
  script:
  - yarn run lint
  allow_failure: true

duplicates:
  stage: test
  script:
  - yarn run duplicates
  allow_failure: true

pages:
  stage: deploy
  environment:
    name: production
    url: https:/omeryagmurlu.gitlab.io/algoriv/
  script:
  - mkdir .public
  - cp -r dist .public
  - mv .public public
  only:
  - production
  artifacts:
    paths:
    - public
  only:
  - master

win-binary:
  image: electronuserland/electron-builder:wine
  stage: deploy
  script:
  - yarn run package-win
  artifacts:
    paths:
    - release

linux-binary:
  image: electronuserland/electron-builder:wine
  stage: deploy
  script:
  - yarn run package-linux
  artifacts:
    paths:
    - release
