# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:7.10.0

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - yarn install --production=false
  - yarn run build:prod
  artifacts:
    paths:
    - node_modules/
    - dist

test:
  stage: test
  script:
  - yarn run test
  allow_failure: true

lint:
  stage: test
  script:
  - yarn run lint
  allow_failure: true

duplicates:
  stage: test
  script:
  - yarn run duplicates
  allow_failure: true

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r dist .public
  - cp -r index.html .public
  - mv .public public
  only:
  - master
  artifacts:
    paths:
    - public
  only:
  - master

win-binary:
  stage: deploy
  before_script:
  - add-apt-repository ppa:ubuntu-wine/ppa -y && apt-get update -qq && apt-get install --no-install-recommends -y wine1.8
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
  - apt-get update
  - apt-get install --no-install-recommends -y mono-devel ca-certificates-mono
  script:
  - yarn run package-win
  artifacts:
    paths:
    - release

linux-binary:
  stage: deploy
  script:
  - yarn run package-linux
  artifacts:
    paths:
    - release
